# File              : docker-compose.yml
# Author            : Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date              : Fri  1 Feb 21:02:37 2019
# Last Modified Date: Thu  7 Feb 16:11:30 2019
# Last Modified By  : Matthieu Petiteau <mpetiteau.pro@gmail.com>

version: "3"

services:
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
            args:
                DOMAIN: ${NGX_DOMAIN}
                FLASK: ${FLASK_APP_NAME}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
        links:
            - flask_app:flask_app
    flask_app:
        restart: always
        build:
            context: ./core
            dockerfile: Dockerfile
        expose:
            - "5000"
        volumes:
            - .:/usr/src/app
        environment:
            - FLASK_ENV=${FLASK_ENV}
            - FLASK_SESSION_KEY=${FLASK_SESSION_KEY}
